In [7]:
import pandas

In [8]:
import pandas as pd

In [9]:
import numpy as np

In [15]:
pd.read_csv("\data\Homicidios_2018.csv")

,Fecha,Departamento,Municipio,Día,Hora,Barrio,Zona,Clase de sitio,Arma empleada,Móvil Agresor,Móvil Victima,Edad,Sexo,Estado civil,País de nacimiento,Clase de empleado,Profesión,Escolaridad,Código DANE,Cantidad
0,01/01/2018 12:00:00 AM,AMAZONAS,LETICIA (CT),Lunes,9:45:00,ESPERANZA,URBANA,VIAS PUBLICAS,ARMA BLANCA / CORTOPUNZANTE,A PIE,A PIE,16.0,MASCULINO,SOLTERO,BRASIL,EMPLEADO PARTICULAR,-,SECUNDARIA,91001000.0,1
1,01/01/2018 12:00:00 AM,AMAZONAS,LETICIA (CT),Lunes,9:45:00,ESPERANZA,URBANA,VIAS PUBLICAS,ARMA BLANCA / CORTOPUNZANTE,A PIE,A PIE,17.0,MASCULINO,SOLTERO,BRASIL,EMPLEADO PARTICULAR,-,SECUNDARIA,91001000.0,1
2,01/01/2018 12:00:00 AM,ANTIOQUIA,ANDES,Lunes,8:30:00,ALTO DEL CEDRON,RURAL,VIAS PUBLICAS,ARMA DE FUEGO,A PIE,A PIE,26.0,MASCULINO,SOLTERO,COLOMBIA,INDEPENDIENTE,-,PRIMARIA,5034000.0,1
3,01/01/2018 12:00:00 AM,ANTIOQUIA,ANDES,Lunes,2:30:00,PARQUE PRINCIPAL,RURAL,PARQUES,ARMA BLANCA / CORTOPUNZANTE,A PIE,A PIE,30.0,MASCULINO,SOLTERO,COLOMBIA,AGRICULTOR,-,PRIMARIA,5034000.0,1
4,01/01/2018 12:00:00 AM,ANTIOQUIA,ANORÍ,Lunes,3:30:00,TENCHE,RURAL,"BARES, CANTINAS Y SIMILARES",ARMA BLANCA / CORTOPUNZANTE,A PIE,A PIE,25.0,MASCULINO,UNION LIBRE,COLOMBIA,INDEPENDIENTE,-,PRIMARIA,5040000.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4961,12/12/2018 12:00:00 AM,SANTANDER,BARRANCABERMEJA,Miércoles,20:09:00,MIRADORES DEL CACIQUE,URBANA,VIAS PUBLICAS,ARMA DE FUEGO,PASAJERO MOTOCICLETA,A PIE,58.0,MASCULINO,SOLTERO,COLOMBIA,EMPLEADO PARTICULAR,-,PRIMARIA,68081000.0,1
4962,12/12/2018 12:00:00 AM,VALLE,CALI (CT),Miércoles,19:47:00,REPUBLICA ISRAEL E16,URBANA,VIAS PUBLICAS,ARMA DE FUEGO,A PIE,A PIE,32.0,FEMENINO,SOLTERO,COLOMBIA,AMA DE CASA,-,SECUNDARIA,76001000.0,1
4963,12/12/2018 12:00:00 AM,VALLE,CALI (CT),Miércoles,19:47:00,REPUBLICA ISRAEL E16,URBANA,VIAS PUBLICAS,ARMA DE FUEGO,A PIE,A PIE,39.0,MASCULINO,SOLTERO,COLOMBIA,EMPLEADO PARTICULAR,-,SECUNDARIA,76001000.0,1
4964,12/12/2018 12:00:00 AM,VALLE,GUADALAJARA DE BUGA,Miércoles,17:45:00,CORR. CHAMBIMBAL/CAMPIÑ,RURAL,FINCAS Y SIMILARES,ARMA BLANCA / CORTOPUNZANTE,A PIE,A PIE,16.0,MASCULINO,SOLTERO,COLOMBIA,DESEMPLEADO,-,SECUNDARIA,76111000.0,1
4965,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12667

In [17]:
Homicidios_df = pd.read_csv("\data\Homicidios_2018.csv")

In [50]:
Homicidios_df

,Fecha,Departamento,Municipio,Día,Hora,Barrio,Zona,Clase de sitio,Arma empleada,Móvil Agresor,Móvil Victima,Edad,Sexo,Estado civil,País de nacimiento,Clase de empleado,Profesión,Escolaridad,Código DANE,Cantidad
0,01/01/2018 12:00:00 AM,AMAZONAS,LETICIA (CT),Lunes,9:45:00,ESPERANZA,URBANA,VIAS PUBLICAS,ARMA BLANCA / CORTOPUNZANTE,A PIE,A PIE,16.0,MASCULINO,SOLTERO,BRASIL,EMPLEADO PARTICULAR,-,SECUNDARIA,91001000.0,1
1,01/01/2018 12:00:00 AM,AMAZONAS,LETICIA (CT),Lunes,9:45:00,ESPERANZA,URBANA,VIAS PUBLICAS,ARMA BLANCA / CORTOPUNZANTE,A PIE,A PIE,17.0,MASCULINO,SOLTERO,BRASIL,EMPLEADO PARTICULAR,-,SECUNDARIA,91001000.0,1
2,01/01/2018 12:00:00 AM,ANTIOQUIA,ANDES,Lunes,8:30:00,ALTO DEL CEDRON,RURAL,VIAS PUBLICAS,ARMA DE FUEGO,A PIE,A PIE,26.0,MASCULINO,SOLTERO,COLOMBIA,INDEPENDIENTE,-,PRIMARIA,5034000.0,1
3,01/01/2018 12:00:00 AM,ANTIOQUIA,ANDES,Lunes,2:30:00,PARQUE PRINCIPAL,RURAL,PARQUES,ARMA BLANCA / CORTOPUNZANTE,A PIE,A PIE,30.0,MASCULINO,SOLTERO,COLOMBIA,AGRICULTOR,-,PRIMARIA,5034000.0,1
4,01/01/2018 12:00:00 AM,ANTIOQUIA,ANORÍ,Lunes,3:30:00,TENCHE,RURAL,"BARES, CANTINAS Y SIMILARES",ARMA BLANCA / CORTOPUNZANTE,A PIE,A PIE,25.0,MASCULINO,UNION LIBRE,COLOMBIA,INDEPENDIENTE,-,PRIMARIA,5040000.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4961,12/12/2018 12:00:00 AM,SANTANDER,BARRANCABERMEJA,Miércoles,20:09:00,MIRADORES DEL CACIQUE,URBANA,VIAS PUBLICAS,ARMA DE FUEGO,PASAJERO MOTOCICLETA,A PIE,58.0,MASCULINO,SOLTERO,COLOMBIA,EMPLEADO PARTICULAR,-,PRIMARIA,68081000.0,1
4962,12/12/2018 12:00:00 AM,VALLE,CALI (CT),Miércoles,19:47:00,REPUBLICA ISRAEL E16,URBANA,VIAS PUBLICAS,ARMA DE FUEGO,A PIE,A PIE,32.0,FEMENINO,SOLTERO,COLOMBIA,AMA DE CASA,-,SECUNDARIA,76001000.0,1
4963,12/12/2018 12:00:00 AM,VALLE,CALI (CT),Miércoles,19:47:00,REPUBLICA ISRAEL E16,URBANA,VIAS PUBLICAS,ARMA DE FUEGO,A PIE,A PIE,39.0,MASCULINO,SOLTERO,COLOMBIA,EMPLEADO PARTICULAR,-,SECUNDARIA,76001000.0,1
4964,12/12/2018 12:00:00 AM,VALLE,GUADALAJARA DE BUGA,Miércoles,17:45:00,CORR. CHAMBIMBAL/CAMPIÑ,RURAL,FINCAS Y SIMILARES,ARMA BLANCA / CORTOPUNZANTE,A PIE,A PIE,16.0,MASCULINO,SOLTERO,COLOMBIA,DESEMPLEADO,-,SECUNDARIA,76111000.0,1
4965,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12667

In [19]:
Homicidios_df.head()

,Fecha,Departamento,Municipio,Día,Hora,Barrio,Zona,Clase de sitio,Arma empleada,Móvil Agresor,Móvil Victima,Edad,Sexo,Estado civil,País de nacimiento,Clase de empleado,Profesión,Escolaridad,Código DANE,Cantidad
0,01/01/2018 12:00:00 AM,AMAZONAS,LETICIA (CT),Lunes,9:45:00,ESPERANZA,URBANA,VIAS PUBLICAS,ARMA BLANCA / CORTOPUNZANTE,A PIE,A PIE,16.0,MASCULINO,SOLTERO,BRASIL,EMPLEADO PARTICULAR,-,SECUNDARIA,91001000.0,1
1,01/01/2018 12:00:00 AM,AMAZONAS,LETICIA (CT),Lunes,9:45:00,ESPERANZA,URBANA,VIAS PUBLICAS,ARMA BLANCA / CORTOPUNZANTE,A PIE,A PIE,17.0,MASCULINO,SOLTERO,BRASIL,EMPLEADO PARTICULAR,-,SECUNDARIA,91001000.0,1
2,01/01/2018 12:00:00 AM,ANTIOQUIA,ANDES,Lunes,8:30:00,ALTO DEL CEDRON,RURAL,VIAS PUBLICAS,ARMA DE FUEGO,A PIE,A PIE,26.0,MASCULINO,SOLTERO,COLOMBIA,INDEPENDIENTE,-,PRIMARIA,5034000.0,1
3,01/01/2018 12:00:00 AM,ANTIOQUIA,ANDES,Lunes,2:30:00,PARQUE PRINCIPAL,RURAL,PARQUES,ARMA BLANCA / CORTOPUNZANTE,A PIE,A PIE,30.0,MASCULINO,SOLTERO,COLOMBIA,AGRICULTOR,-,PRIMARIA,5034000.0,1
4,01/01/2018 12:00:00 AM,ANTIOQUIA,ANORÍ,Lunes,3:30:00,TENCHE,RURAL,"BARES, CANTINAS Y SIMILARES",ARMA BLANCA / CORTOPUNZANTE,A PIE,A PIE,25.0,MASCULINO,UNION LIBRE,COLOMBIA,INDEPENDIENTE,-,PRIMARIA,5040000.0,1

In [20]:
type(Homicidios_df)

pandas.core.frame.DataFrame

In [23]:
Homicidios_df.dtypes

Fecha                  object
Departamento           object
Municipio              object
Día                    object
Hora                   object
Barrio                 object
Zona                   object
Clase de sitio         object
Arma empleada          object
Móvil Agresor          object
Móvil Victima          object
Edad                  float64
Sexo                   object
Estado civil           object
País de nacimiento     object
Clase de empleado      object
Profesión              object
Escolaridad            object
Código DANE           float64
Cantidad                int64
dtype: object

In [24]:
pip install --upgrade google-cloud-bigquery[pandas]

Collecting google-cloud-bigquery[pandas]
  Downloading google_cloud_bigquery-1.26.1-py2.py3-none-any.whl (170 kB)
Collecting google-cloud-core<2.0dev,>=1.1.0
  Downloading google_cloud_core-1.4.1-py2.py3-none-any.whl (26 kB)
Collecting google-resumable-media<2.0dev,>=0.5.0
  Downloading google_resumable_media-0.7.1-py2.py3-none-any.whl (42 kB)
Collecting google-api-core<2.0dev,>=1.21.0
  Downloading google_api_core-1.22.1-py2.py3-none-any.whl (91 kB)
Requirement already satisfied, skipping upgrade: six<2.0.0dev,>=1.13.0 in c:\users\saracmque\anaconda3\lib\site-packages (from google-cloud-bigquery[pandas]) (1.15.0)
Requirement already satisfied, skipping upgrade: pandas>=0.17.1; extra == "pandas" in c:\users\saracmque\anaconda3\lib\site-packages (from google-cloud-bigquery[pandas]) (1.0.5)
Collecting google-crc32c<0.2dev,>=0.1.0; python_version >= "3.5"
  Downloading google-crc32c-0.1.0.tar.gz (10 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Requirement already satisfied, skipping upgrade: requests<3.0.0dev,>=2.18.0 in c:\users\saracmque\anaconda3\lib\site-packages (from google-api-core<2.0dev,>=1.21.0->google-cloud-bigquery[pandas]) (2.24.0)
Requirement already satisfied, skipping upgrade: setuptools>=34.0.0 in c:\users\saracmque\anaconda3\lib\site-packages (from google-api-core<2.0dev,>=1.21.0->google-cloud-bigquery[pandas]) (49.2.0.post20200714)
Requirement already satisfied, skipping upgrade: pytz in c:\users\saracmque\anaconda3\lib\site-packages (from google-api-core<2.0dev,>=1.21.0->google-cloud-bigquery[pandas]) (2020.1)
Collecting google-auth<2.0dev,>=1.19.1
  Downloading google_auth-1.20.1-py2.py3-none-any.whl (91 kB)
Collecting googleapis-common-protos<2.0dev,>=1.6.0
  Downloading googleapis_common_protos-1.52.0-py2.py3-none-any.whl (100 kB)
Collecting protobuf>=3.12.0
  Downloading protobuf-3.12.4-py2.py3-none-any.whl (443 kB)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.6.1 in c:\users\saracmque\anaconda3\lib\site-packages (from pandas>=0.17.1; extra == "pandas"->google-cloud-bigquery[pandas]) (2.8.1)
Requirement already satisfied, skipping upgrade: numpy>=1.13.3 in c:\users\saracmque\anaconda3\lib\site-packages (from pandas>=0.17.1; extra == "pandas"->google-cloud-bigquery[pandas]) (1.18.5)
Requirement already satisfied, skipping upgrade: cffi>=1.0.0 in c:\users\saracmque\anaconda3\lib\site-packages (from google-crc32c<0.2dev,>=0.1.0; python_version >= "3.5"->google-resumable-media<2.0dev,>=0.5.0->google-cloud-bigquery[pandas]) (1.14.0)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\saracmque\anaconda3\lib\site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<2.0dev,>=1.21.0->google-cloud-bigquery[pandas]) (1.25.9)
Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in c:\users\saracmque\anaconda3\lib\site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<2.0dev,>=1.21.0->google-cloud-bigquery[pandas]) (2.10)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in c:\users\saracmque\anaconda3\lib\site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<2.0dev,>=1.21.0->google-cloud-bigquery[pandas]) (2020.6.20)
Requirement already satisfied, skipping upgrade: chardet<4,>=3.0.2 in c:\users\saracmque\anaconda3\lib\site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<2.0dev,>=1.21.0->google-cloud-bigquery[pandas]) (3.0.4)
Collecting rsa<5,>=3.1.4; python_version >= "3.5"
  Downloading rsa-4.6-py3-none-any.whl (47 kB)
Collecting cachetools<5.0,>=2.0.0
  Downloading cachetools-4.1.1-py3-none-any.whl (10 kB)
Collecting pyasn1-modules>=0.2.1
  Downloading pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
Requirement already satisfied, skipping upgrade: pycparser in c:\users\saracmque\anaconda3\lib\site-packages (from cffi>=1.0.0->google-crc32c<0.2dev,>=0.1.0; python_version >= "3.5"->google-resumable-media<2.0dev,>=0.5.0->google-cloud-bigquery[pandas]) (2.20)
Collecting pyasn1>=0.1.3
  Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Building wheels for collected packages: google-crc32c
  Building wheel for google-crc32c (PEP 517): started
  Building wheel for google-crc32c (PEP 517): finished with status 'done'
  Created wheel for google-crc32c: filename=google_crc32c-0.1.0-py3-none-any.whl size=9818 sha256=91801a49692ac7b77b82a36bceff4e1f4e1940fa1595f2828b55525b46590543
  Stored in directory: c:\users\saracmque\appdata\local\pip\cache\wheels\2a\2e\73\c2bfa476c8ec3655ceb5acccf6adc774c8356a2a8fedf123ff
Successfully built google-crc32c
Installing collected packages: pyasn1, rsa, cachetools, pyasn1-modules, google-auth, protobuf, googleapis-common-protos, google-api-core, google-cloud-core, google-crc32c, google-resumable-media, google-cloud-bigquery
Successfully installed cachetools-4.1.1 google-api-core-1.22.1 google-auth-1.20.1 google-cloud-bigquery-1.26.1 google-cloud-core-1.4.1 google-crc32c-0.1.0 google-resumable-media-0.7.1 googleapis-common-protos-1.52.0 protobuf-3.12.4 pyasn1-0.4.8 pyasn1-modules-0.2.8 rsa-4.6
Note: you may need to restart the kernel to use updated packages.

In [ ]:
¿Qué problemas de calidad de los datos evidencia?

In [ ]:
Campos tipo fecha no tienen el formato por ejemplo campo fecha.

In [ ]:
Formato de hora para campo hora no se tiene un formato de hora.

In [ ]:
Entendiendo que los datos de barrio,zona,etc estàn los datos del maestros y muestra su descripciòn. Sino estos deben tener un id para cada maestro y mostrar la descripciòn del campo.

In [ ]:
Existen lineas sin datos

In [ ]:
 ¿Cómo podrías resolverlos?

In [ ]:
Realizar una mineria de datos, y con BigQuery con where donde columnas no esten en null Y DAR FORMATO  campos de fecha y hora.

In [ ]:
Dar formato de fecha y hora a estos campos

In [ ]:
Entendiendo que los datos de barrio,zona,etc estàn los datos del maestros y muestra su descripciòn. Sino estos deben tener un id para cada maestro y mostrar la descripciòn del campo.

In [ ]:
 algunas consultas en SQL para explorar los datos en Bigquery

In [ ]:
BigQuery con where donde columnas no esten en null Y DAR FORMATO  campos de fecha y hora.

In [25]:
%load_ext google.cloud.bigquery

In [30]:
Homicidios_df.columns

Index(['Fecha', 'Departamento', 'Municipio', 'Día', 'Hora', 'Barrio', 'Zona',
       'Clase de sitio', 'Arma empleada', 'Móvil Agresor', 'Móvil Victima',
       'Edad', 'Sexo', 'Estado civil', 'País de nacimiento',
       'Clase de empleado', 'Profesión', 'Escolaridad', 'Código DANE',
       'Cantidad'],
      dtype='object')

In [31]:
grouped_data = Homicidios_df.groupby('Municipio')

In [42]:
species_counts = Homicidios_df.groupby('Municipio')['Cantidad'].count()
print(species_counts)

Municipio
ABREGO            2
ACACÍAS           6
ACANDÍ            7
ACEVEDO           4
ACHÍ              2
                 ..
YUMBO            37
ZARAGOZA          7
ZARZAL            9
ZIPAQUIRÁ         2
ZONA BANANERA    11
Name: Cantidad, Length: 582, dtype: int64

In [41]:
⦁ ¿Cuáles fueron los principales municipios con mayor cantidad de asesinatos por mes?

Object `mes` not found.

In [ ]:
⦁ ¿Cuáles fueron los principales municipios con mayor cantidad de asesinatos por mes

In [ ]:
YUMBO             37 y ZONA BANANERA    11

In [ ]:
Para Bogotá, qué barrios reportaron mayor cantidad de asesinatos entre las 6 de la noche y las 12 de la noche.

In [ ]:
ALBANIA E-3                           18:00:00    1

VISTA HERMOSA SECTOR EL ESPINAL E-19  20:10:00    1

Sin descripciòn de barrio tenemos estos:
                                      21:20:00    1
                                      21:40:00    1

In [47]:
species_counts = Homicidios_df.groupby('Barrio')['Municipio'].count()
print(species_counts)

Barrio
07 DE AGOSTO         1
1 DE MAYO            2
11 DE ABRIL          1
11 DE NOVIEMBRE      2
12 DE OCTUBRE        1
                    ..
ZONA CENTRO          4
ZONA INDUSTRIAL      3
ZONA RURAL           4
ZONA TOLERANCIA      1
ZUNGO EMBARCADERO    1
Name: Municipio, Length: 2947, dtype: int64

In [48]:
grouped_data.describe()

               Edad                                                        \
              count       mean        std   min    25%   50%    75%   max
Municipio
ABREGO          2.0  41.000000  25.455844  23.0  32.00  41.0  50.00  59.0
ACACÍAS         6.0  28.333333   7.257180  15.0  27.25  29.5  33.25  35.0
ACANDÍ          7.0  32.000000   5.773503  24.0  30.00  31.0  33.00  43.0
ACEVEDO         4.0  48.250000  18.246004  26.0  38.75  49.0  58.50  69.0
ACHÍ            2.0  36.000000   8.485281  30.0  33.00  36.0  39.00  42.0
...             ...        ...        ...   ...    ...   ...    ...   ...
YUMBO          37.0  27.162162  10.210326   5.0  21.00  25.0  29.00  50.0
ZARAGOZA        7.0  31.142857   9.668309  20.0  22.00  35.0  38.00  43.0
ZARZAL          9.0  35.444444  12.340088  22.0  27.00  31.0  45.00  59.0
ZIPAQUIRÁ       2.0  28.000000   9.899495  21.0  24.50  28.0  31.50  35.0
ZONA BANANERA  11.0  34.636364   9.821128  19.0  31.00  33.0  39.50  55.0

              Código DANE              ...                         Cantidad  \
                    count        mean  ...         75%         max    count
Municipio                              ...
ABREGO                2.0  54003000.0  ...  54003000.0  54003000.0      2.0
ACACÍAS               6.0  50006000.0  ...  50006000.0  50006000.0      6.0
ACANDÍ                7.0  27006000.0  ...  27006000.0  27006000.0      7.0
ACEVEDO               4.0  41006000.0  ...  41006000.0  41006000.0      4.0
ACHÍ                  2.0  13006000.0  ...  13006000.0  13006000.0      2.0
...                   ...         ...  ...         ...         ...      ...
YUMBO                37.0  76892000.0  ...  76892000.0  76892000.0     37.0
ZARAGOZA              7.0   5895000.0  ...   5895000.0   5895000.0      7.0
ZARZAL                9.0  76895000.0  ...  76895000.0  76895000.0      9.0
ZIPAQUIRÁ             2.0  25899000.0  ...  25899000.0  25899000.0      2.0
ZONA BANANERA        11.0  47980000.0  ...  47980000.0  47980000.0     11.0


              mean  std  min  25%  50%  75%  max
Municipio
ABREGO         1.0  0.0  1.0  1.0  1.0  1.0  1.0
ACACÍAS        1.0  0.0  1.0  1.0  1.0  1.0  1.0
ACANDÍ         1.0  0.0  1.0  1.0  1.0  1.0  1.0
ACEVEDO        1.0  0.0  1.0  1.0  1.0  1.0  1.0
ACHÍ           1.0  0.0  1.0  1.0  1.0  1.0  1.0
...            ...  ...  ...  ...  ...  ...  ...
YUMBO          1.0  0.0  1.0  1.0  1.0  1.0  1.0
ZARAGOZA       1.0  0.0  1.0  1.0  1.0  1.0  1.0
ZARZAL         1.0  0.0  1.0  1.0  1.0  1.0  1.0
ZIPAQUIRÁ      1.0  0.0  1.0  1.0  1.0  1.0  1.0
ZONA BANANERA  1.0  0.0  1.0  1.0  1.0  1.0  1.0

[582 rows x 24 columns]

In [ ]:
¿Qué otros conocimientos puede extraer de este conjunto de datos?

In [51]:
grouped_data2 = Homicidios_df.groupby(['Municipio','Hora'])

In [62]:
grouped_data2.mean()

                        Edad  Código DANE  Cantidad
Municipio     Hora
ABREGO        10:30:00  59.0   54003000.0       1.0
              23:08:00  23.0   54003000.0       1.0
ACACÍAS       16:45:00  31.0   50006000.0       1.0
              1:40:00   35.0   50006000.0       1.0
              23:05:00  31.0   50006000.0       1.0
...                      ...          ...       ...
ZONA BANANERA 1:50:00   55.0   47980000.0       1.0
              22:40:00  39.0   47980000.0       1.0
              5:00:00   30.0   47980000.0       1.0
              7:00:00   28.0   47980000.0       1.0
              7:15:00   32.0   47980000.0       1.0

[4129 rows x 3 columns]

In [77]:
Homicidios_df.groupby(['Municipio','Barrio','Hora'])['Hora'].count()['BOGOTÁ D.C. (CT)']

Barrio                                Hora
ACIP E-8                              15:30:00    1
ALBANIA E-3                           18:00:00    1
ALCALA E-16                           13:30:00    1
ALFA E-19                             14:15:00    1
ALQUERIAS DE LA FRAGUA E-8            16:14:00    1
                                                 ..
VISTA HERMOSA SECTOR EL ESPINAL E-19  20:10:00    1
VITELMA E-4                           11:00:00    1
VOTO NACIONAL E-14                    15:15:00    1
                                      21:20:00    1
                                      21:40:00    1
Name: Hora, Length: 419, dtype: int64

In [ ]:
¿Tendría sentido un modelo de aprendizaje automático para apoyar a la fuerza policial en su trabajo?

In [ ]:
Claroque si, es de utilidad para su labor.

In [ ]:
¿Qué tipo de modelo elegiría (regresión, clasificación, agrupamiento)?

In [ ]:
Agrupamiento

In [ ]:
¿Cómo implementaría su modelo? Proponer una arquitectura y explicarla.